# Generated by Django 4.2.5 on 2024-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='energyinsight',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
