# Generated by Django 4.2.5 on 2024-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_energyinsight_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='intensity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
