# Generated by Django 4.2.5 on 2024-01-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_energyinsight_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinsight',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
    ]
